### ISSUE TITLE
Distinguish between NA and 0 in case counts in original df and bring through to later dfs.

### ISSUE THREAD

**Issue by wendtke** [nmonhait/westnile_epi#12]
Currently, the map shows a county with NA counts as gray, but that county might actually have 0 cases in that particular year for that gender. 

In the original data, we need to use the `expand.grid()` function to obtain all possible combinations of counties ("NAMES"), gender ("gender"), and year ("year"). Then, we `full_join` with our filtered data to obtain '0's for all combinations of county name, gender, and year that are truly '0' and 'NA' for any combination that is truly missing. 

Then, we feed the new df through, and the map should accurately depict '0's vs. 'NA's.

**Comment by wendtke** [comment]
We could possibly use the `dplyr` version: `expand()`. I am currently comparing the two options.

**Comment by nmonhait** [comment]
working on this now

**Comment by wendtke** [comment]
Look at my code on the top of helper.R

**Comment by nmonhait** [comment]
there are not 0s in the dataset at all- full_county_gender_year has NAs only

**Comment by wendtke** [comment]
@jessyjj 
Let's add this to the report and presentation: There are no '0's in the original dataset; we do not know if the data treated 'NA's and '0's the same way, although they mean different things. We decided not to change the 'NA's to '0's because 1) the map would show the same information and 2) 'NA's can still be meaningful. It is possible that data were not collected in certain counties or that there were no cases to report; we cannot know.
