### ISSUE TITLE
Clean and explore dataset 

### ISSUE THREAD

**Issue by nmonhait** [nmonhait/westnile_epi#3]
@randyxun

clean and explore the dataset (it is already relatively clean)
please find indicators to ultimately go on our shiny dashboard
we envision something like this https://asheshwor.shinyapps.io/np-quake/

**Comment by wendtke** [comment]
I tried to assign Randy's username to this issue, but it did not show. @nmonhait Can you try? I think the email would be clearer with the assignment instead of the mention.

**Comment by randyxun** [comment]
Try it now

**Comment by randyxun** [comment]
Or I guess I could have just done it lol

**Comment by wendtke** [comment]
We may also want to find census data for Illinois to see if particular groups are overrepresented. I am not sure how this could blend with our map app, though.

**Comment by wendtke** [comment]
@randyxun 
can you clean the data to make all columns the appropriate class? and clean up variables? I consolidated everything in a new Rmd. We will source specific chunks from there into the Shiny app.
